---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{R echo=TRUE}
knitr::opts_chunk$set(fig.path='figure/')
```

## Loading and preprocessing the data

We're going to load the data from the local filesystem making sure to change the date datatype to Date.  We also create a data set that has removed the records with NA for steps.

```{R echo=TRUE}

stepsData <- read.csv("activity.csv" , colClasses=c("numeric", "Date", "numeric"))
stepsDataWithoutNA <- subset(stepsData, !is.na(steps))
stepsPerDayWithoutNA <- aggregate(stepsDataWithoutNA$steps, FUN=sum, by=list(stepsDataWithoutNA$date))

```


## What is mean total number of steps taken per day?
Here's the histogram of the number of steps taken per day.

```{R echo=TRUE}
hist(stepsPerDayWithoutNA$x, xlab="Number of Steps Taken", main="Histogram of Number of Steps Taken in a Day")
```

The mean number of steps per day is `r format(mean(stepsPerDayWithoutNA$x), digits=1, nsmall=2)` and the median is `r format(median(stepsPerDayWithoutNA$x), digits=1, nsmall=2)`.

## What is the average daily activity pattern?
This shows us the average steps taken by interval.

```{R echo=TRUE}
averageStepsPerIntervalWithoutNA <- aggregate(stepsDataWithoutNA$steps, FUN=mean, by=list(stepsDataWithoutNA$interval))

plot(averageStepsPerIntervalWithoutNA$Group.1, averageStepsPerIntervalWithoutNA$x, type="l", xlab="Interval (across all days)", ylab="Average Steps Taken", main="Average Steps Taken by Interval")
```

The interval with the maximum average number of steps is `r subset(averageStepsPerIntervalWithoutNA, x==max(averageStepsPerIntervalWithoutNA$x))$Group.1 `.

## Imputing missing values

The total number of rows that have missing values is `r nrow(subset(stepsData, is.na(steps)))`.

To replace the NA values, we're going to use the average steps by interval.  We're doing this because there's no data for 10/1/2012.

Let's see what the histogram looks like as well.

```{R echo=TRUE}


stepsDataCorrected <- merge(stepsData, averageStepsPerIntervalWithoutNA, by.x="interval", by.y="Group.1")
stepsDataCorrected[is.na(stepsDataCorrected$steps),]$steps=stepsDataCorrected[is.na(stepsDataCorrected$steps),]$x
stepsPerDayWithNA <- aggregate(stepsDataCorrected$steps, FUN=sum, by=list(stepsDataCorrected$date))

hist(stepsPerDayWithNA$x, xlab="Number of Steps Taken", main="Histogram of Number of Steps Taken in a Day (Corrected)")
```
The mean number of steps per day is `r format(mean(stepsPerDayWithNA$x), digits=1, nsmall=2)` and the median is `r format(median(stepsPerDayWithNA$x), digits=1, nsmall=2)`.

The mean and median are not appreciably different with the corrected data.

## Are there differences in activity patterns between weekdays and weekends?

Let's break the data out by weekend versus weekday.

```{R echo=TRUE}
stepsDataCorrected$WeekDay = weekdays(stepsDataCorrected$date)
stepsDataCorrected[stepsDataCorrected$WeekDay == "Saturday",]$WeekDay= "weekend"
stepsDataCorrected[stepsDataCorrected$WeekDay == "Sunday",]$WeekDay= "weekend"
stepsDataCorrected[stepsDataCorrected$WeekDay != "weekend",]$WeekDay= "weekday"

averageAcrossIntervalAndWeekDay <- aggregate(stepsDataCorrected$steps, FUN=mean, by=list(stepsDataCorrected$interval, stepsDataCorrected$WeekDay))

library(lattice)
with(averageAcrossIntervalAndWeekDay, xyplot(x~Group.1|Group.2,group= Group.2, type="l", layout=c(1,2), xlab="Interval", ylab="Number of Steps"))
```